# Generated by Django 5.0.1 on 2025-05-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-year'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AddField(
            model_name='car',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО'),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_interval',
            field=models.IntegerField(default=180, verbose_name='Интервал ТО (дней)'),
        ),
        migrations.AddField(
            model_name='car',
            name='maintenance_notes',
            field=models.TextField(blank=True, verbose_name='Заметки по обслуживанию'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег (км)'),
        ),
        migrations.AddField(
            model_name='car',
            name='needs_maintenance',
            field=models.BooleanField(default=False, verbose_name='Требуется ТО'),
        ),
        migrations.AddField(
            model_name='car',
            name='next_maintenance_mileage',
            field=models.IntegerField(default=10000, verbose_name='Пробег до следующего ТО (км)'),
        ),
    ]
