# Generated by Django 5.0.1 on 2025-05-30 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_rental_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='penalties',
        ),
        migrations.AddField(
            model_name='rental',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promo'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='expected_return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
