# Generated by Django 5.0.1 on 2025-05-30 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_rental_discount_remove_rental_penalties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='promo',
            new_name='promo_code',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='details',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='year',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobvacancy',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +375 (XX) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promo',
            name='discount_percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='rental',
            name='expected_return_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
