# Generated by Django 5.0.1 on 2025-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_promo_rental_promo_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AddField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='rental',
            name='penalties',
            field=models.ManyToManyField(blank=True, to='main.penalty'),
        ),
    ]
