# Generated by Django 5.0.1 on 2025-05-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_rental_options_rental_notes_rental_penalties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='maintenance_interval',
        ),
        migrations.RemoveField(
            model_name='car',
            name='maintenance_notes',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='needs_maintenance',
        ),
        migrations.RemoveField(
            model_name='car',
            name='next_maintenance_mileage',
        ),
    ]
